# Week 1: File

In [35]:
with open('test3.txt', 'w+') as file:
    file.writelines(['Hello','World','!'])

In [39]:
try:
    with open('test4.txt', 'r') as file:
        pass
except Exception as e:
    print(e)

[Errno 2] No such file or directory: 'test4.txt'


In [42]:
with open('test3.txt', 'r+') as file:
    lines = reversed(file.readlines())
    file.seek(0)
    file.writelines(lines)
    file.seek(0)
    print(file.read())
    

9
8
7
6
5
4
3
2
1



In [50]:
with open('test3.txt','r+') as file:
    for i in range(2):
        next(file)
        
    print(file.readline(10))

78901234



# Week 2: csv, json

In [133]:
import csv

# Read file csv
with open('weatherAUS.csv') as file:
    reader = csv.reader(file)
    for index, line in enumerate(reader):
        if index == 3:
            break
            
        print(line)
        
print()

['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow']
['1/12/08', 'Albury', '13.4', '22.9', '0.6', 'NA', 'NA', 'W', '44', 'W', 'WNW', '20', '24', '71', '22', '1007.7', '1007.1', '8', 'NA', '16.9', '21.8', 'No', '0', 'No']
['2/12/08', 'Albury', '7.4', '25.1', '0', 'NA', 'NA', 'WNW', '44', 'NNW', 'WSW', '4', '22', '44', '25', '1010.6', '1007.8', 'NA', 'NA', '17.2', '24.3', 'No', '0', 'No']



In [87]:
with open('weatherAUS.csv') as file:
    reader = csv.DictReader(file, fieldnames=('Date', 'Location', 'MinTemp'))
    for index, row in enumerate(reader):
        if index == 0:
            continue
        if index == 4:
            break
            
        print(row)
        
    print(index)
    
# Write file csv

with open('test.csv', 'w') as file:
    writer = csv.writer(file)
    writer.writerow(['name', 'age', 'postcode'])
    writer.writerows([
        ['Tung', 25, 5000],
        ['Mai', 26, 5001],
        ['Thao', 22, 100000]
    ])



{'Date': '1/12/08', 'Location': 'Albury', 'MinTemp': '13.4', None: ['22.9', '0.6', 'NA', 'NA', 'W', '44', 'W', 'WNW', '20', '24', '71', '22', '1007.7', '1007.1', '8', 'NA', '16.9', '21.8', 'No', '0', 'No']}
{'Date': '2/12/08', 'Location': 'Albury', 'MinTemp': '7.4', None: ['25.1', '0', 'NA', 'NA', 'WNW', '44', 'NNW', 'WSW', '4', '22', '44', '25', '1010.6', '1007.8', 'NA', 'NA', '17.2', '24.3', 'No', '0', 'No']}
{'Date': '3/12/08', 'Location': 'Albury', 'MinTemp': '12.9', None: ['25.7', '0', 'NA', 'NA', 'WSW', '46', 'W', 'WSW', '19', '26', '38', '30', '1007.6', '1008.7', 'NA', '2', '21', '23.2', 'No', '0', 'No']}
4


In [104]:
import json
import pprint

data = {'name':'Tung', 'age':25, 'postcode':5000}

with open('newFile.json','r+') as file:
    jstr = file.read()
    jdata = json.loads(jstr)
    
    file.seek(0)
    
    jdata.append(data)
    json.dump(jdata,file)
    

In [119]:
with open('donuts.json', 'r') as file:
    string = file.read()
    jsondata = json.loads(string)
    
    pprint.pprint(jsondata)
    
    for donut in jsondata:
        topping = donut['topping']
        print(topping)

[{'batters': {'batter': [{'id': '1001', 'type': 'Regular'},
                         {'id': '1002', 'type': 'Chocolate'},
                         {'id': '1003', 'type': 'Blueberry'},
                         {'id': '1004', 'type': "Devil's Food"}]},
  'id': '0001',
  'name': 'Cake',
  'ppu': 0.55,
  'topping': [{'id': '5001', 'type': 'None'},
              {'id': '5002', 'type': 'Glazed'},
              {'id': '5005', 'type': 'Sugar'},
              {'id': '5007', 'type': 'Powdered Sugar'},
              {'id': '5006', 'type': 'Chocolate with Sprinkles'},
              {'id': '5003', 'type': 'Chocolate'},
              {'id': '5004', 'type': 'Maple'}],
  'type': 'donut'},
 {'batters': {'batter': [{'id': '1001', 'type': 'Regular'}]},
  'id': '0002',
  'name': 'Raised',
  'ppu': 0.55,
  'topping': [{'id': '5001', 'type': 'None'},
              {'id': '5002', 'type': 'Glazed'},
              {'id': '5005', 'type': 'Sugar'},
              {'id': '5003', 'type': 'Chocolate'},
             

In [120]:
with open('test.csv', 'w') as outfile:
    writer = csv.writer(outfile, delimiter=',', quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['hi', 'dude'])
    writer.writerow(['hi2', 'dude2'])

In [132]:
import numpy as np

uniform = np.random.uniform(low = 1, high = 10, size = (3,4))
integer = np.random.randint(low = 1, high = 10, size = (3,4))

print(uniform)
print(integer)

[[8.55110242 5.01612965 7.52050344 7.35273203]
 [4.63341805 6.25192325 3.10737915 8.66914605]
 [3.0691787  5.34324297 9.18993609 6.12670053]]
[[1 1 8 1]
 [9 9 4 4]
 [6 6 3 7]]


In [137]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [141]:
b = np.array([[ 3, 12,  5, 65],
       [13, 90,  2, 49],
       [35, 79,  1,  8]])

c = b[::-1, 1:3]
print(c)

[[79  1]
 [90  2]
 [12  5]]


In [143]:
# Example with two-dimensional array

#Create a two-dimensional array
m1 = np.arange(24).reshape((6, 4))
print("m1 =\n", m1)

#Split into two equal arrays 
mS1,mS2 = np.split(m1,2,axis = 1);#[2]index for rows, the two first  
print("mS1 =\n", mS1)
print("mS2 =\n", mS2)

m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
mS1 =
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
mS2 =
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


In [162]:
import pandas as pd

#Construct a series from a dictionary
a = pd.Series({2:'orange', 3:'apple', 1:'nectarin', 4:'strawberry'})
print(a[3])

b = pd.Series([[3,4,5],[6,7,8]], index=['mot', 'hai'])
b = b.set_axis(['ba', 'bon'])
print(b.index)
print(b.values)

apple
Index(['ba', 'bon'], dtype='object')
[list([3, 4, 5]) list([6, 7, 8])]


In [163]:
df1 = pd.DataFrame(np.array([[6.5, 90.3], [3.6, 3.2]]))
df1

0     1
0  6.5  90.3
1  3.6   3.2

In [256]:
df2 = pd.DataFrame([[6.5, 90.3,1], [3.6, 3.2,2], [8.4, 2.2,9], [9.8, 1.1,0]], columns=['money', 'age','bla'], index=['a','b','c','d'])
df2.loc[['a', 'b'], ['age', 'money']]

print(df2.iloc[-2:])

   money  age  bla
c    8.4  2.2    9
d    9.8  1.1    0


In [252]:
df3 = pd.DataFrame({"Mot":[1,2,3,4], "Hai": [6,7,8,9]}, index=['a', 'b', 'c', 'd'], columns=['One', 'Two', 'Mot', 'Hai'])
df3.loc[df3.Mot <= 2]

One  Two  Mot  Hai
a  NaN  NaN    1    6
b  NaN  NaN    2    7

In [175]:
colors = pd.Series(['yellow', 'white', 'black', 'black', 'white', 'red', 'yellow', 'red', 'purple','black', 'black', 'red'])

print(colors.unique().sum())
print(colors.value_counts())
print(colors.isin([
    'yellow',
    'Black'
]).sum())

yellowwhiteblackredpurple
black     4
red       3
yellow    2
white     2
purple    1
dtype: int64
2


In [258]:
s_maxTemp = pd.Series(np.round(np.random.uniform(20, 45,11),2))
s_minTemp = pd.Series(np.round(np.random.uniform(-5, 19,11),2))
s_area = pd.Series([12368, 9990, 15826, 6418, 3258, 414.13, 814.2, 261.8, 714, 957, 1696])
s_cities = pd.Series(['Sydney','Melbourne','Brisbane','Perth','Adelaide','Gold Coast','Canberra','Newcastle',
          'Wollongong','Logan City','Hobart'])
s_density = pd.Series([4627345, 4246375, 2189878, 1896548,1225235, 591473, 367752, 308308, 292190, 282673, 218000])
s_state = pd.Series(['New South Wales', 'Victoria','Queensland', 'Western Australia','South Australia',
                     'Queensland','Australian Capital Territory','New South Wales','New South Wales', 
                     'Queensland', 'Tasmania'])
                     
s_unemployed_rate = pd.Series([4.3, 4.9, np.nan, np.nan, 7.3, 6.4, 3.5, 4.3, 4.3, 6.4, 6.2])
df_pop = pd.DataFrame({'cities':s_cities,'area': s_area, 'density': s_density, 'state':s_state,
                       'unemployed_rate':s_unemployed_rate, 'min_Temp':s_minTemp, 'max_Temp':s_maxTemp })
df_pop

cities      area  density                         state  \
0       Sydney  12368.00  4627345               New South Wales   
1    Melbourne   9990.00  4246375                      Victoria   
2     Brisbane  15826.00  2189878                    Queensland   
3        Perth   6418.00  1896548             Western Australia   
4     Adelaide   3258.00  1225235               South Australia   
5   Gold Coast    414.13   591473                    Queensland   
6     Canberra    814.20   367752  Australian Capital Territory   
7    Newcastle    261.80   308308               New South Wales   
8   Wollongong    714.00   292190               New South Wales   
9   Logan City    957.00   282673                    Queensland   
10      Hobart   1696.00   218000                      Tasmania   

    unemployed_rate  min_Temp  max_Temp  
0               4.3     -0.69     27.93  
1               4.9     -1.72     22.73  
2               NaN     -2.71     23.94  
3               NaN     -4.77     25.56  
4               7.3      2.78     30.38  
5               6.4     13.58     27.95  
6               3.5     -2.36     42.30  
7               4.3     18.44     20.49  
8               4.3      2.84     20.28  
9               6.4      8.39     32.23  
10              6.2     -1.96     22.18

In [262]:
df_pop.iloc[-2:]

cities    area  density       state  unemployed_rate  min_Temp  \
9   Logan City   957.0   282673  Queensland              6.4      8.39   
10      Hobart  1696.0   218000    Tasmania              6.2     -1.96   

    max_Temp  
9      32.23  
10     22.18

In [263]:
df_pop.iloc[:5, :2]

cities     area
0     Sydney  12368.0
1  Melbourne   9990.0
2   Brisbane  15826.0
3      Perth   6418.0
4   Adelaide   3258.0

In [31]:
import pandas as pd
import numpy as np

s_maxTemp = pd.Series(np.round(np.random.uniform(20, 45,11),2))
s_minTemp = pd.Series(np.round(np.random.uniform(-5, 19,11),2))
s_area = pd.Series([12368, 9990, 15826, 6418, 3258, 414.13, 814.2, 261.8, 714, 957, 1696])
s_cities = pd.Series(['Sydney','Melbourne','Brisbane','Perth','Adelaide','Gold Coast','Canberra','Newcastle',
          'Wollongong','Logan City','Hobart'])
s_density = pd.Series([4627345, np.nan, 2189878, 1896548,1225235, 591473, 367752, 308308, 292190, 282673, 218000])
s_state = pd.Series(['New South Wales', 'Victoria','Queensland', 'Western Australia','South Australia',
                     'Queensland','Australian Capital Territory','New South Wales','New South Wales', 
                     'Queensland', 'Tasmania'])
                     
s_unemployed_rate = pd.Series([4.3, 4.9, np.nan, np.nan, 7.3, 6.4, 3.5, 4.3, 4.3, 6.4, 6.2])
df = pd.DataFrame({'cities':s_cities,'area': s_area, 'density': s_density, 'state':s_state,
                       'unemployed_rate':s_unemployed_rate, 'min_Temp':s_minTemp, 'max_Temp':s_maxTemp })

df[df.isna().any(axis=1)]
print(df[df['unemployed_rate'].isnull()])
print(df['state'].unique())

print(df.iloc[::4, 0])
print()
print(df.loc[::4, 'cities'])
print(df.loc[::4])

print()
print(df['cities'])
print()

print(df[0])

     cities     area    density              state  unemployed_rate  min_Temp  \
2  Brisbane  15826.0  2189878.0         Queensland              NaN      9.16   
3     Perth   6418.0  1896548.0  Western Australia              NaN      6.95   

   max_Temp  
2     24.13  
3     43.61  
['New South Wales' 'Victoria' 'Queensland' 'Western Australia'
 'South Australia' 'Australian Capital Territory' 'Tasmania']
0        Sydney
4      Adelaide
8    Wollongong
Name: cities, dtype: object

0        Sydney
4      Adelaide
8    Wollongong
Name: cities, dtype: object
       cities     area    density            state  unemployed_rate  min_Temp  \
0      Sydney  12368.0  4627345.0  New South Wales              4.3     -4.96   
4    Adelaide   3258.0  1225235.0  South Australia              7.3      8.77   
8  Wollongong    714.0   292190.0  New South Wales              4.3     -1.76   

   max_Temp  
0     34.11  
4     35.05  
8     30.77  

0         Sydney
1      Melbourne
2       Brisbane
3  

KeyError: 0