In [63]:
import numpy as np

#Addition
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(3)
print('a1=\n', a1)
print('a2=\n', a2)

print('Addition a1 + 5 =\n', a1+5)
print ('np.add a1 + 5 =\n', np.add(a1,5))
#Addition two arrays 
print ('np.add a1 + a2 =\n', np.add(a1,a2))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a2=
 [0 1 2]
Addition a1 + 5 =
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
np.add a1 + 5 =
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
np.add a1 + a2 =
 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [60]:
#Subtraction
print('a1=\n', a1)

print('Subtraction a1 - 5 =\n', a1-5)
print ('np.subtract a1 - 5 =\n', np.subtract(a1,5))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Subtraction a1 - 5 =
 [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
np.subtract a1 - 5 =
 [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]


In [61]:
#Negative
print('a1=\n', a1)

print('Negative -a1 =\n', -a1)
print ('np.negative a1  =\n', np.negative(a1))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Negative -a1 =
 [[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]
np.negative a1  =
 [[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]


In [64]:
#Multiplication
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(3)
print('a1=\n', a1)
print('a2=\n', a2)

print('Multiplication a1*a2 =\n', a1*a2)
print ('np.multiply (a1,a2)  =\n', np.multiply(a1,a2))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a2=
 [0 1 2]
Multiplication a1*a2 =
 [[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]
np.multiply (a1,a2)  =
 [[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


In [65]:
#Division
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(3)
print('a1=\n', a1)

print('Division a1/2 =\n', a1/2)
print ('np.divide (a1,2)  =\n', np.divide(a1,2))
print('a2=\n', a2)
print('np.divide (a1,a2) =\n', np.divide(a1,a2))
#NOTE: Be careful with the division by zero! Anaconda give you a warning and the result of dividing 
# a number by zero will be infinity or nan 0/0

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Division a1/2 =
 [[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
np.divide (a1,2)  =
 [[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
a2=
 [0 1 2]
np.divide (a1,a2) =
 [[nan 1.  1. ]
 [inf 4.  2.5]
 [inf 7.  4. ]]


/var/folders/pw/s8535kh50y9b39g5wwk9_83h0000gn/T/ipykernel_29757/3363323915.py:9: RuntimeWarning: divide by zero encountered in true_divide
  print('np.divide (a1,a2) =\n', np.divide(a1,a2))
/var/folders/pw/s8535kh50y9b39g5wwk9_83h0000gn/T/ipykernel_29757/3363323915.py:9: RuntimeWarning: invalid value encountered in true_divide
  print('np.divide (a1,a2) =\n', np.divide(a1,a2))


In [68]:
#Integer Division
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(3)
print('a1=\n', a1)

print('Integer division a1//2 =\n', a1//2)
print ('np.divide (a1,2)  =\n', np.floor_divide(a1,2))
print('a2=\n', a2)
print('np.floor_divide (a1,a2)=\n', np.floor_divide(a1,a2))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Integer division a1//2 =
 [[0 0 1]
 [1 2 2]
 [3 3 4]]
np.divide (a1,2)  =
 [[0 0 1]
 [1 2 2]
 [3 3 4]]
a2=
 [0 1 2]
np.floor_divide (a1,a2)=
 [[0 1 1]
 [0 4 2]
 [0 7 4]]


/var/folders/pw/s8535kh50y9b39g5wwk9_83h0000gn/T/ipykernel_29757/3886769588.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print('np.floor_divide (a1,a2)=\n', np.floor_divide(a1,a2))


In [69]:
#Exponentiation
a1 = np.arange(9).reshape(3,3)
print('a1=\n', a1)

print('Exponentiation a1**=\n', a1**2)
print ('np.power (a1,2)=\n', np.power(a1,2))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Exponentiation a1**=
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
np.power (a1,2)=
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [70]:
#Modulo (division remainder)
a1 = np.arange(9).reshape(3,3)
print('a1=\n', a1)

print('Modulo a1/3=\n', a1%3)
print ('np.mod (a1,3)=\n', np.mod(a1,3))

a1=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Modulo a1/3=
 [[0 1 2]
 [0 1 2]
 [0 1 2]]
np.mod (a1,3)=
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


In [57]:
#Example: Find the minimum and maximum number in an array 
a1=np.random.uniform(-1000, 1000, size=(3, 4)) #generate randomly a number
print("a1= \n",a1)
print()

#If you don't specify in the function max or min if you want the max/min of each row or column
# it will find the max or min in the entire array
print("Minimum number in all a1: ", np.min(a1))
print("Maximum number in all a1: ", np.max(a1))
print()

#looking per column axis=0 
print("Minimum number per column in a1: ", np.min(a1, axis=0))
print("Maximum number per column in a1: ", np.max(a1, axis=0))
print()

#looking per row axis=1
print("Minimum number per row in a1: ", np.min(a1, axis=1))
print("Maximum number per row in a1: ", np.max(a1, axis=1))

a1= 
 [[-480.70769348 -449.76501387 -345.03059813  -11.7362066 ]
 [-747.21066907 -195.05511892  662.21830222 -152.9759633 ]
 [-862.20776092 -725.28984769  832.70857124  792.16748152]]

Minimum number in all a1:  -862.2077609165506
Maximum number in all a1:  832.7085712446271

Minimum number per column in a1:  [-862.20776092 -725.28984769 -345.03059813 -152.9759633 ]
Maximum number per column in a1:  [-480.70769348 -195.05511892  832.70857124  792.16748152]

Minimum number per row in a1:  [-480.70769348 -747.21066907 -862.20776092]
Maximum number per row in a1:  [-11.7362066  662.21830222 832.70857124]


In [58]:
#Transpose of an array 
a2= np.random.randint(low=-10, high=10, size=(2, 3))
print('a2 =\n', a2)

print('Transpose of a2 =\n', np.transpose(a2) )

a2 =
 [[  8 -10   0]
 [ -6   3  -8]]
Transpose of a2 =
 [[  8  -6]
 [-10   3]
 [  0  -8]]


In [72]:
temp = np.arange(5,13,2)
print(temp)

[ 5  7  9 11]


In [76]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [83]:
a2 = np.array([[3, 12, 5, 65],[13, 90, 2, 49], [35, 79, 1, 8]])

a2[1:3, 1:3]

array([[90,  2],
       [79,  1]])

In [84]:
a1d = np.arange(0,13).reshape(3,5)
a1d

ValueError: cannot reshape array of size 13 into shape (3,5)

In [92]:
vec = np.arange(4)
print('vec = ', vec)

print(np.split(vec,4))

vec =  [0 1 2 3]
[array([0]), array([1]), array([2]), array([3])]


In [93]:
# Example of np.split in one-dimensional array into 5 parts
vec = np.arange(10.0)
print(vec)

(print(np.split(vec, [3, 5, 6, 10])))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[array([0., 1., 2.]), array([3., 4.]), array([5.]), array([6., 7., 8., 9.]), array([], dtype=float64)]


In [104]:
# Example with two-dimensional array

#Create a two-dimensional array
m1 = np.arange(24).reshape((6, 4))
print("m1 =\n", m1)

#Split into two equal arrays 
print(np.split(m1,6)) # split into 2 equal array


m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]


In [110]:
# Example with two-dimensional array

#Create a two-dimensional array
m1 = np.arange(24).reshape((6, 4))
print("m1 =\n", m1)

#Split the first two rows from the rest 
print(np.split(m1,[2,3]));

m1 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [144]:
a1= np.array(
    [[  4,  -8,   7,   4],
    [ 32, -89,  67,   2],
    [ 58, -87,  46,  94]])

'''
 1.[ 58, -87,  46,  94]  
   [ 32, -89,  67,   2]  
   [  4,  -8,   7,   4] 

 2. [ 32, -89,  67,   2]

 3.[[ 7],
    [67],
    [46]]

 4.[[-89,  67],
    [-87,  46]]  

 5.[[ 7,  4],
   [67,  2]]
'''

#1
a1_1 = a1[::-1]
print(a1_1)
print('---')

#2 - First way
a1_2 = a1[1]
print("First way")
print(a1_2)
print(type(a1_2))
print()

#2 - Second way
a1_2_2 = a1[1:2]
print("Second way")
print(a1_2_2)
print(type(a1_2_2))
print('---')

#3
a1_3 = a1[:,2:3]
print(a1_3)
print('---')

#4
a1_4 = a1[1:,1:3]
print(a1_4)
print('---')

#5
a1_5 = a1[:2, 2:]
print(a1_5)


a1= np.array([[  4,  -8,   7,   4],
              [ 32, -89,  67,   2],
              [ 58, -87,  46,  94]])
print ('a1 = \n',a1)
print('1. = \n', a1[::-1])
print('2. = \n', a1[1:2])
print('3. = \n', a1[:,2:3])
print('4. = \n', a1[1:3,1:3])
print('5. = \n', a1[0:2,2:4])

[[ 58 -87  46  94]
 [ 32 -89  67   2]
 [  4  -8   7   4]]
---
First way
[ 32 -89  67   2]
<class 'numpy.ndarray'>

Second way
[[ 32 -89  67   2]]
<class 'numpy.ndarray'>
---
[[ 7]
 [67]
 [46]]
---
[[-89  67]
 [-87  46]]
---
[[ 7  4]
 [67  2]]
a1 = 
 [[  4  -8   7   4]
 [ 32 -89  67   2]
 [ 58 -87  46  94]]
1. = 
 [[ 58 -87  46  94]
 [ 32 -89  67   2]
 [  4  -8   7   4]]
2. = 
 [[ 32 -89  67   2]]
3. = 
 [[ 7]
 [67]
 [46]]
4. = 
 [[-89  67]
 [-87  46]]
5. = 
 [[ 7  4]
 [67  2]]


In [158]:
a1= np.array(
    [[  4,  -8,   7,   4],
    [ 32, -89,  67,   2],
    [ 58, -87,  46,  94]])

#2 - First way
a1_2 = a1[1]
print("First way")
print(a1_2)
print(type(a1_2))

print()

#2 - Second way
a1_2_2 = a1[1:2]
print("Second way")
print(a1_2_2)
print(type(a1_2_2))

print(a1_2[0])
print(a1_2_2[0][0])


First way
[ 32 -89  67   2]
<class 'numpy.ndarray'>

Second way
[[ 32 -89  67   2]]
<class 'numpy.ndarray'>
32
32
